// Registers the service worker generated by vite-plugin-pwa and shows a
// toast when a new version is ready, so users get updates without needing
// to know to hard-refresh (especially important once installed as a PWA).
export async function registerServiceWorker() {
  if (!("serviceWorker" in navigator)) return;

  try {
    const { registerSW } = await import("virtual:pwa-register");
    const { toast } = await import("react-toastify");

    registerSW({
      immediate: true,
      onNeedRefresh() {
        toast.info("A new version is available. Refresh to update.", {
          autoClose: false,
          closeOnClick: true,
        });
      },
      onOfflineReady() {
        // App shell cached — no toast needed, this is a silent background win.
      },
    });
  } catch (err) {
    // virtual:pwa-register is unavailable in dev with devOptions disabled —
    // that's expected and safe to ignore.
  }
}
